name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: tests.py
      id: tests-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: tests.py
        setup-command: sudo -H pip3 install --upgrade setuptools ; sudo -H pip3 install
          --upgrade pip; sudo -H pip3 install -r requirements.txt
        command: python3 -m unittest tests.py
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-PY_RESULTS: "${{steps.tests-py.outputs.result}}"
      with:
        runners: tests-py
